In [1]:
import numpy as np  
import pandas as pd


In [2]:
"""1) Lire les donn´ees `a l’aide de la biblioth`eque python pandas et faire un r´esum´e des donn´ees
(combiens de donn´ees, combien de classes, r´epartition par classe, ”range” des donn´ees, histogramme des valeurs...)"""


iris = pd.read_csv('https://datahub.io/machine-learning/iris/r/iris.csv');
iris


sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
iris.info() 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
iris[0:10] 

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [5]:
"""2) Extraire de ce fichier 2 tableaux de type numpy, le premier appeler X avec 4 colonnes et
autant de ligne que de mesures et le second appel´e Y un tableau de label de classe `a prendre
parmi les valeurs 0,1 ou 2 """

X= iris.iloc[:, :-1].values

#iris['class']=iris['class'].astype('category')
#Y=iris['class'].cat.codes.values

Y = iris.iloc[:,-1].values
Y= np.where(Y=='Iris-setosa',0 , np.where(Y=='Iris-versicolor',1,2))

print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers



2023-10-10 21:17:32.364443: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-10-10 21:17:32.364587: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [7]:

model = keras.Sequential()

model.add(layers.Input(shape=(4,)))

model.add(layers.Dense(8, activation='relu'))

model.add(layers.Dense(1, activation='linear'))

2023-10-10 21:18:04.541558: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-10-10 21:18:04.541683: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-10-10 21:18:04.541807: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (newtown): /proc/driver/nvidia/version does not exist


In [8]:
model.get_weights()

[array([[ 0.26911658, -0.5491217 , -0.2441712 ,  0.11942631, -0.0617969 ,
          0.10409242,  0.34576815,  0.45844477],
        [-0.66321135, -0.37881148, -0.17373133, -0.06794459, -0.604627  ,
          0.40257996,  0.40448803, -0.29348063],
        [-0.6607048 ,  0.30527312, -0.6443223 , -0.2504799 , -0.5407599 ,
         -0.3436782 ,  0.3645584 ,  0.61280745],
        [-0.35999712,  0.03103948,  0.6409263 , -0.456142  ,  0.3361786 ,
          0.48788148, -0.5718469 ,  0.27525854]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.76245505],
        [-0.65419084],
        [ 0.57852554],
        [-0.31214112],
        [-0.3596629 ],
        [-0.5707552 ],
        [-0.482154  ],
        [ 0.69304466]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
# Compiler le modèle en spécifiant la fonction de perte, l'optimiseur
model.compile(loss='mse', optimizer='adam')

In [10]:
# Entraîner le modèle sur les données d'entraînement
model.fit(X, Y, epochs=150, batch_size=150, verbose=2)

Epoch 1/150
1/1 - 1s - loss: 0.4428 - 735ms/epoch - 735ms/step
Epoch 2/150
1/1 - 0s - loss: 0.4129 - 4ms/epoch - 4ms/step
Epoch 3/150
1/1 - 0s - loss: 0.3858 - 4ms/epoch - 4ms/step
Epoch 4/150
1/1 - 0s - loss: 0.3617 - 4ms/epoch - 4ms/step
Epoch 5/150
1/1 - 0s - loss: 0.3405 - 3ms/epoch - 3ms/step
Epoch 6/150
1/1 - 0s - loss: 0.3222 - 3ms/epoch - 3ms/step
Epoch 7/150
1/1 - 0s - loss: 0.3067 - 3ms/epoch - 3ms/step
Epoch 8/150
1/1 - 0s - loss: 0.2939 - 3ms/epoch - 3ms/step
Epoch 9/150
1/1 - 0s - loss: 0.2836 - 4ms/epoch - 4ms/step
Epoch 10/150
1/1 - 0s - loss: 0.2757 - 3ms/epoch - 3ms/step
Epoch 11/150
1/1 - 0s - loss: 0.2697 - 3ms/epoch - 3ms/step
Epoch 12/150
1/1 - 0s - loss: 0.2655 - 3ms/epoch - 3ms/step
Epoch 13/150
1/1 - 0s - loss: 0.2626 - 3ms/epoch - 3ms/step
Epoch 14/150
1/1 - 0s - loss: 0.2608 - 5ms/epoch - 5ms/step
Epoch 15/150
1/1 - 0s - loss: 0.2595 - 4ms/epoch - 4ms/step
Epoch 16/150
1/1 - 0s - loss: 0.2586 - 3ms/epoch - 3ms/step
Epoch 17/150
1/1 - 0s - loss: 0.2578 - 3ms/ep

In [11]:
Ypred=model.predict(X)
Ypred.round()

array([[-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [ 0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 1.],
      

In [14]:
Matrice_confusion=tf.math.confusion_matrix(Y,Ypred)
#On affiche la matrice de confusion

In [15]:
Matrice_confusion

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[50,  0,  0],
       [ 3, 47,  0],
       [ 0, 42,  8]], dtype=int32)>

In [16]:
len(Y)

150

In [21]:
print(Matrice_confusion/150*100)
#On l'affiche en pourcentages

tf.Tensor(
[[33.33333333  0.          0.        ]
 [ 2.         31.33333333  0.        ]
 [ 0.         28.          5.33333333]], shape=(3, 3), dtype=float64)
