In [3]:
import numpy as np
import pandas as pd

iris = pd.read_csv('https://datahub.io/machine-learning/iris/r/iris.csv')
iris

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
import tensorflow as tf #impossible à appeler
from tensorflow import keras
from tensorflow.keras import layers

model=keras.Sequential()
model.add(layers.Input(shape=(4,)))
model.add(layers.Dense(8,activation='relu'))
model.add(layers.Dense(1,activation='linear'))
model.summary







X=iris.iloc[:,:-1].values
Y=iris.iloc[:,-1].values
Y=np.where(Y=='Iris-setosa',0,np.where(Y=='Iris-versicolor',1,2))

In [7]:
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
model.compile(loss='mse',optimizer='adam')
model.fit(X,Y,epochs=50,batch_size=150,verbose=2)


Epoch 1/50
1/1 - 1s - loss: 1.5881 - 812ms/epoch - 812ms/step
Epoch 2/50
1/1 - 0s - loss: 1.5067 - 3ms/epoch - 3ms/step
Epoch 3/50
1/1 - 0s - loss: 1.4275 - 3ms/epoch - 3ms/step
Epoch 4/50
1/1 - 0s - loss: 1.3505 - 4ms/epoch - 4ms/step
Epoch 5/50
1/1 - 0s - loss: 1.2757 - 3ms/epoch - 3ms/step
Epoch 6/50
1/1 - 0s - loss: 1.2038 - 3ms/epoch - 3ms/step
Epoch 7/50
1/1 - 0s - loss: 1.1349 - 3ms/epoch - 3ms/step
Epoch 8/50
1/1 - 0s - loss: 1.0693 - 3ms/epoch - 3ms/step
Epoch 9/50
1/1 - 0s - loss: 1.0067 - 3ms/epoch - 3ms/step
Epoch 10/50
1/1 - 0s - loss: 0.9468 - 3ms/epoch - 3ms/step
Epoch 11/50
1/1 - 0s - loss: 0.8900 - 4ms/epoch - 4ms/step
Epoch 12/50
1/1 - 0s - loss: 0.8360 - 3ms/epoch - 3ms/step
Epoch 13/50
1/1 - 0s - loss: 0.7853 - 3ms/epoch - 3ms/step
Epoch 14/50
1/1 - 0s - loss: 0.7377 - 3ms/epoch - 3ms/step
Epoch 15/50
1/1 - 0s - loss: 0.6935 - 3ms/epoch - 3ms/step
Epoch 16/50
1/1 - 0s - loss: 0.6521 - 4ms/epoch - 4ms/step
Epoch 17/50
1/1 - 0s - loss: 0.6136 - 4ms/epoch - 4ms/step
Ep

In [9]:
Ypred=model.predict(X)
Ypred.round()

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-0.],
       [-0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-0.],
       [-1.],
       [-0.],
       [-0.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
      

In [10]:
Ypred

array([[-0.82684094],
       [-0.6945145 ],
       [-0.7449078 ],
       [-0.60461307],
       [-0.8264568 ],
       [-0.6523236 ],
       [-0.6352843 ],
       [-0.73770744],
       [-0.5798301 ],
       [-0.7390192 ],
       [-0.8708019 ],
       [-0.64818996],
       [-0.7522085 ],
       [-0.8098017 ],
       [-1.1573803 ],
       [-0.9061504 ],
       [-0.8569688 ],
       [-0.7499689 ],
       [-0.76793575],
       [-0.75518954],
       [-0.7120974 ],
       [-0.6595236 ],
       [-0.9543895 ],
       [-0.40515304],
       [-0.49470633],
       [-0.61137027],
       [-0.5328024 ],
       [-0.79485756],
       [-0.82722497],
       [-0.59142375],
       [-0.59180784],
       [-0.6606759 ],
       [-0.9844937 ],
       [-1.0351114 ],
       [-0.7390192 ],
       [-0.8536032 ],
       [-0.9547147 ],
       [-0.7390192 ],
       [-0.64978546],
       [-0.75688547],
       [-0.78195214],
       [-0.46053344],
       [-0.68737346],
       [-0.39785224],
       [-0.47367257],
       [-0

In [19]:
# confusion matrix in sklearn
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import numpy as np
import itertools

# actual values
actual=Y


# predicted values
predicted=np.concatenate(np.count_nonzero(Ypred.round()==0)+np.count_nonzero(Ypred.round()==-1),np.count_nonzero(Ypred.round()==1),np.count_nonzero(Ypred.round()==2))

# confusion matrix
cnf_matrix = confusion_matrix(actual,predicted)
#print('Matrice de confusion : \n',cnf_matrix)

classes = range(0,2)
plt.figure()

plt.imshow(cnf_matrix, interpolation='nearest',cmap='Oranges')
plt.colorbar()
tick_marks = np.arange(len(classes))
plt.xticks(tick_marks, classes)
plt.yticks(tick_marks, classes)

for i, j in itertools.product(range(cnf_matrix.shape[0]), range(cnf_matrix.shape[1])):
    plt.text(j, i, cnf_matrix[i, j],
             horizontalalignment="center",
             color="white" if cnf_matrix[i, j] > ( cnf_matrix.max() / 2) else "black")

plt.ylabel('Vrais labels')
plt.xlabel('Labels prédits')
plt.show()

# outcome values order in sklearn
tn, fp, fn ,tp = confusion_matrix(actual,predicted).reshape(-1)
print('Valeurs de TN, FP, FN, TP : \n',tn, fp, fn, tp)

# classification report for precision, recall f1-score and accuracy
matrix = classification_report(actual,predicted)
print('Rapport de Classification  : \n',matrix)

TypeError: 'int' object is not iterable

In [16]:
type(Ypred)

numpy.ndarray