#### Exercice 3 AN TD06

we have this table showing the observed speed in relation to time

In [8]:
from tabulate import tabulate
print(tabulate([["t","v"],[0,2.5],[10,2],[20,1.7],[30,1.2]],headers="firstrow"))

  t    v
---  ---
  0  2.5
 10  2
 20  1.7
 30  1.2


we want to find a polynomial approximation in the sense of discrete least squares by a polynomial , of different degree each time

In [3]:
import numpy as np
import sympy as sp

In [62]:
t = sp.symbols('t')
T1=sp.Matrix([[1],[t]])
T1
T2=sp.Matrix([[1],[t],[t**2]])
T2
T3=sp.Matrix([[1],[t],[t**2],[t**3]])
T3

Matrix([
[   1],
[   t],
[t**2],
[t**3]])

#### a) of degree less than 1

In [82]:
B=np.array([[1,0],[1,10],[1,20],[1,30]])


Y=(np.array([[2.5],[2],[1.7],[1.2]]))


print(Y,B)

[[2.5]
 [2. ]
 [1.7]
 [1.2]] [[ 1  0]
 [ 1 10]
 [ 1 20]
 [ 1 30]]


In [83]:
BT=np.transpose(B)
BT

array([[ 1,  1,  1,  1],
       [ 0, 10, 20, 30]])

In [84]:
BT@B

array([[   4,   60],
       [  60, 1400]])

In [85]:
BT@Y

array([[ 7.4],
       [90. ]])

In [86]:
np.transpose(np.linalg.solve(BT@B,BT@Y))@T1

Matrix([[2.48 - 0.042*t]])

#### b) of degree less than 2

In [87]:
B=np.array([[1,0,0],[1,10,100],[1,20,400],[1,30,900]])
B

array([[  1,   0,   0],
       [  1,  10, 100],
       [  1,  20, 400],
       [  1,  30, 900]])

In [88]:
BT=np.transpose(B)
BT

array([[  1,   1,   1,   1],
       [  0,  10,  20,  30],
       [  0, 100, 400, 900]])

In [89]:
BT@B

array([[     4,     60,   1400],
       [    60,   1400,  36000],
       [  1400,  36000, 980000]])

In [90]:
np.transpose(np.linalg.solve(BT@B,BT@Y))@T2

Matrix([[1.49880108324396e-18*t**2 - 0.0420000000000001*t + 2.48]])

#### c) of degree less than 3

In [91]:
B=np.array([[1,0,0,0],[1,10,100,1000],[1,20,200,20**3],[1,30,900,30**3]])
B

array([[    1,     0,     0,     0],
       [    1,    10,   100,  1000],
       [    1,    20,   200,  8000],
       [    1,    30,   900, 27000]])

In [92]:
BT=np.transpose(B)
BT

array([[    1,     1,     1,     1],
       [    0,    10,    20,    30],
       [    0,   100,   200,   900],
       [    0,  1000,  8000, 27000]])

In [96]:
print('Q(t)=', np.transpose(np.linalg.solve(BT@B,BT@Y))@T3)

Q(t)= Matrix([[3.33333333333334e-5*t**3 - 0.000999999999999999*t**2 - 0.0433333333333335*t + 2.5]])
